import Head from "next/head";
import Spinner from "@/components/UI/Spinner/Spinner";
import dynamic from "next/dynamic";

const Main = dynamic(() => import("../components/Main"), {
  loading: () => <Spinner />,
  ssr: false,
});
const Home = () => {
  return (
    <>
      <Head>
        <title>Tropic bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://telegram.org/js/telegram-web-app.js"
        ></script>
      </Head>
      <Main />
    </>
  );
};

export default Home;
