import Head from "next/head";
import Main from "@/components/Main";

const Home = () => {
  return (
    <>
      <Head>
        <title>Tropic bot</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          async
          src="https://telegram.org/js/telegram-web-app.js"
        ></script>
      </Head>
      <Main />
    </>
  );
};

export default Home;
